import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Provider from '@/context/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex w-full flex-col h-screen'>
        <Provider>
          <Header/>
          <main className='flex h-screen p-4'>
            {children}
          </main>
          <Footer/>
        </Provider>
      </body>
    </html>
  )
}
